version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
  search-module:
    image: vishvajafaldesai/selenium
    container_name: search-module
    depends_on:
      - chrome
    environment:
      - MODULE=search-module.xml
      - BROWSER=chrome
      - SELENIUM_HUB=selenium-hub
  
